### ISSUE TITLE
エラー境界のドキュメントに”うんち うんち うんち”という表記があります

### ISSUE THREAD

**Issue by hasegawa-101** [coji/remix-docs-ja#69]
## 対象のページ
https://react-router-docs-ja.techtalk.jp/how-to/error-boundary

**Comment by coji** [comment]
ありがとうございます。もともとの英文に入っていたのでした笑

こちらの更新でなくなりました。
https://github.com/coji/remix-docs-ja/commit/47d484409220c31a6bc1fa6b1b9b372e1517adfb#diff-9bc4d1dc478458e32985374fc920f54d1ba33747800dce51b355f7b329a913fd
